#!/bin/bash

# very ugly script, but it works so is it really ugly?

while getopts "r:" flag; do
 case $flag in
   r) # handle -r
   RESIZE=true
   RESVAL="$OPTARG"
   ;;
   ?)
   # makes the script throw an error on unrecognised arg
   NUHUH=true
   ;;
 esac
done
filename="$1"
resizename="$3"
if [ "$RESIZE" = "true" ]; then
echo "Resizing and compressing $resizename."
magick "$resizename" -strip -interlace Plane -gaussian-blur 0.05 -resize "$RESVAL"% -quality 95% "$3_comp_res.jpg"
elif [ "$NUHUH" = "true" ]; then
 echo "Syntax is 'compimg (-r (if resizing)) {filename}'."
else
echo "Only compressing $filename."
magick "$filename" -strip -interlace Plane -gaussian-blur 0.05 -quality 95% "$1_comp.jpg"
fi
